Develop
globalgov/qData pull request #157
Opened 2021-04-28 15:31 UTC by henriquesposito

# Description

These minor changes set up a `code_agreements()` function that extracts meaningful information from agreements titles and dates to form a qID. 

## Package

* Added agreements vignette for working with `code_agreements()`

## Correction

* Closed #155 by updating `standardise_titles()` to translate strings to English when API key is provided as an argument

## Connection

* Closed #137 by making `data_contrast()` and `data_source()` return exportable objects
* Added `code_agreements()` function
  * Closed #130 by setting up new `code_agreements()` that extracts meaningful information from agreements titles and dates
  * Setup `code_parties()`, `code_type()`, `code_dates()`, `code_known_agreements()` and `code_linkage()` helper functions
  * Closed #148 by making `code_agreemnts()` more accurate, consistent and parsimoneus.
  * Fixed #154 by allowing `code_agreements()` to take date ranges
  * Added tests for `code_agreements()`

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2021-04-30 15:35 UTC, henriquesposito commented
@jhollway I went through all the files in qData today and addressed many of the lintr, pointblank and codefactor issues/suggestions. The code should be more consistent across the package now. However, I tried to address the three last issues with Code Factor, but I cannot get the functions to work properly when I substitute them to the suggested functions (nor otherwise). Could you please take a quick look at these when you have a bit of time and see if you can deal with them? Thank you.

2021-05-02 12:13 UTC, jhollway requested changes

2021-05-02 12:13 UTC, jhollway commented on vignettes/agreements.Rmd
> +format.
Please start each sentence on a new line. It makes editing (and reading in Rmd) easier.

2021-05-02 12:13 UTC, jhollway commented on vignettes/agreements.Rmd
> +```{r known agreements, eval=FALSE}
chunk names need to be all one word, no spaces

2021-05-02 12:13 UTC, jhollway commented on vignettes/agreements.Rmd
> +```{r comparison}, warning=FALSE, message=FALSE}
double closing brace

2021-05-02 12:13 UTC, jhollway commented on vignettes/agreements.Rmd
> +```{r hand coded data, warning=FALSE, message=FALSE}
chunk names need to be all one word, no spaces

2021-05-02 12:13 UTC, jhollway commented on vignettes/agreements.Rmd
> +```
vignette doesn't run. I've outlined a few possibilities why below.

2021-05-03 09:34 UTC, henriquesposito commented on R/code_agreements.R
> +                                                (ifelse((!is.na(parties) & (type != "A")), paste0(uID, type, "_", line), NA)))))))))))
I added comments between each line to facilitate reading...

2021-05-03 11:06 UTC, henriquesposito commented on R/code_agreements.R
> +  )
I left code and area off for now and will create issues for this on GitHub.

2021-05-03 13:56 UTC, henriquesposito commented on R/code_agreements.R
> +  number <- stringr::str_remove(number, "[:digit:]{4}")
These were added as helper functions, not exported. They are now remove_dates() and order_agreements().

2021-05-03 18:23 UTC, henriquesposito commented on R/code_agreements.R
> +    )
After much wrangling, I was able to adapt the function and add it as a csv internal data for comparison. Now that I have figured it out I will try and do the same for code_linkages().

2021-05-03 18:23 UTC, henriquesposito commented on R/code_agreements.R
> +#' Identify a region or area the treaty title refers to.
Removed code_areas() for now. Will bring it back when we add code_topic().

2021-05-03 19:14 UTC, henriquesposito commented on R/data_export.R
>  #' \dontrun{
Adding donttest here created a CMD error, I left as dontrun for now.

2021-05-05 07:12 UTC, henriquesposito commented on tests/testthat/test_report_data.R
> +                            dataset = "GW"), "list")
@BBieri could you take a look at this and see if you get the functions not to print the output when testing? Thank you.

2021-05-05 08:59 UTC, BBieri commented on tests/testthat/test_report_data.R
> +                            dataset = "GW"), "list")
All done @henriquesposito

2021-05-05 11:43 UTC, henriquesposito commented on DESCRIPTION
>      bibtex,
I agree. However, if we end up split qData into two packages (qData and qCreate) some of these dependencies will be automatically split.

2021-05-05 12:13 UTC, henriquesposito commented on R/code_agreements.R
> +                cap, "", USE.NAMES = !is.null(names(x)))
Now the function calls standardise_titles() there. However, it is a bit slower but not too much.

2021-05-05 17:02 UTC, henriquesposito commented on R/package_get.R
> +        latest <- sapply(latest, function(x) {
I will leave it for now since codefactor does not see it as an issue. I quite like sapply, but understand why it can also generate some warnings.

2021-05-05 17:04 UTC, henriquesposito commented on R/standardise_titles.R
> +                                         !is.na(df[, co]), co][1]
No, I took a look and I think we are not. Would you like me to deprecate the function? I do think it is a little function that might come handy for future data correction and, perhaps, "colllapsing" datasets.

2021-05-05 17:22 UTC, henriquesposito commented on R/utility.R
>                        package = "qData") {
package_tools?

2021-05-06 07:30 UTC, jhollway requested changes

2021-05-06 07:30 UTC, jhollway commented on NEWS.md
> +  * Closed #148 by making `code_agreemnts()` more accurate, consistent and parsimonious
spelling

2021-05-06 07:30 UTC, jhollway commented on R/plot_releases.R
>  #' A plotting function that visualises historical milestones/releases
I'm thinking about migrating this function to migraph... Can do this in the next release though.

2021-05-06 07:30 UTC, jhollway commented on R/report_data.R
> +#' default.
It's a bit ambiguous in the wording how quiet = FALSE should work. "print or don't print" is not only maybe the wrong way around given that the default is not to print, but is also rather colloquially phrased?

2021-05-06 07:30 UTC, jhollway commented on R/standardise_titles.R
> +#' Standardise titles
Maybe we want to separate out a capitalisation helper that can also be used elsewhere, from a standardise_titles() function that not only uses that capitalisation helper but potentially other operations too, like language standardisation?

2021-05-06 07:30 UTC, jhollway commented on R/standardise_titles.R
> +#' of the strings.If an API key is provided as an argument,
Space between sentences

2021-05-06 07:30 UTC, jhollway commented on R/standardise_titles.R
> +                                         !is.na(df[, co]), co][1]
Then maybe migrate this to the resolve script? This makes sure it stays with qData when we migrate various functions to qCreate...

2021-05-06 07:30 UTC, jhollway commented on R/utility.R
>                        package = "qData") {
Sounds good

2021-05-06 07:30 UTC, jhollway commented on DESCRIPTION
>  Suggests:
rmarkdown package required, at least as Suggests, to run the vignettes

2021-05-06 07:30 UTC, jhollway commented on vignettes/agreements.Rmd
> +```
Still doesn't run, this time based on rmarkdown dependency

2021-05-06 07:30 UTC, jhollway commented on R/standardise_dates.R
>  #' qData = qData::standardise_dates(OriginalDate)
Is this example all working now?

2021-05-06 07:30 UTC, jhollway commented on R/code_agreements.R
> +#' Ideally, title variable should come from a qPackage database/dataset
Ideally or required?

2021-05-06 07:30 UTC, jhollway commented on R/code_agreements.R
> +#' Ideally, date variable should come from a qPackage database/dataset
Ditto

2021-05-07 11:32 UTC, henriquesposito commented on R/standardise_dates.R
>  #' qData = qData::standardise_dates(OriginalDate)
Yes, it is, we fixed it in the last PR.

2021-05-07 11:37 UTC, henriquesposito commented on R/code_agreements.R
> +#' Ideally, date variable should come from a qPackage database/dataset
Same answer as above. However, can change if you would like.

2021-05-07 12:00 UTC, henriquesposito commented on R/standardise_titles.R
> +#' Standardise titles
I have started to do that, however, this creates a bit of redundancy. I also see the value in keeping all these features together in one function in this case, as many of these single features (as capitalizations) can be performed with a single call from base (i.e. toupper) or other packages (hmisc::capitalize). What do you think?

2021-05-07 14:52 UTC, henriquesposito commented on R/code_agreements.R
> +  if (!is.null(dataset)) {
@jhollway I have been trying to make code_agreements() return qID as a new variable in the dataset while keeping the dataset name, if dataset argument is present. However, I have not been able to properly do so yet. Could you please take a look at it and see if you are able to find a solution? Thank you.

2021-05-12 14:26 UTC, jhollway commented on README.Rmd
> -
This is great, but maybe add a link to qCreate in here.

2021-05-12 15:23 UTC, BBieri commented on README.Rmd
> -
I put a section header to highlight the paragraph with the link to the new `{qCreate}` package. Does that work or did you have something more specific in mind?

2021-05-14 10:45 UTC, jhollway approved these changes

2021-05-14 10:45 UTC, jhollway commented on R/report_data.R
> +data_source <- function(pkg, database = NULL, dataset = NULL, print = TRUE) {
An alternative to this solution is to avoid using `print` in the function(s) and instead create an object or list of the elements that would then get assigned, or, if no assigned, then it would print. See also `summary()` etc.

2021-05-14 14:48 UTC, henriquesposito commented on R/report_data.R
> +data_source <- function(pkg, database = NULL, dataset = NULL, print = TRUE) {
I have taken a look at this and though I understand the logic of it, I am having issues implementing it. I will open an issue on GitHub for this to try and re-think the print argument sometime in the future when we add the data_evolution() function.

2021-05-14 15:07 UTC, merged