Set up a more informative README document and created vignettes for qData
globalgov/qData pull request #75
Opened 2020-12-10 10:37 UTC by henriquesposito

# Description

These minor changes setup a more informative README document and add vignettes to facilitate for developers and users to work with qData. There were updates to the `import_data()`, `export_data()`, `standardise_dates()` and `get_packages()` functions. Finally, the package name has been changed from qDatr to qData.  

# Package 

- Closes #32 by setting up a more informative README document
- Closes #67 by creating a vignette for developers interested in contribute to the qData ecosystem
- A vignette for users working with qData has also been created and modified. 

# Collection

- Updates `import_data()` by suggesting upper case letters for dataset names and lower case letters for database names. Function documentation and template scripts were modified to reflect these changes. 

# Correction

- Closes #70 by updating `stadardise_dates()` so that extreme future dates are standardised. The function was also updated to accept multiple variable dates as inputs and it standardises separators 
- Updates `export_data()` by making it save datasets as named list elements in a database. The documentation and preparation scripts attached to the function have also been altered to reflect these changes. 

# Connection

- Updates the `get_packages()` function to find registered contributors to the qData ecosystem

# Checklist:

- [ ] I have commented my code in-line, particularly in hard-to-understand areas
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [ ] The package builds on my OS without issues
- [ ] My changes generate no new warnings
- [ ] PR checks all pass for latest commit
- [ ] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [ ] I have updated NEWS.md
- [ ] I have given this pull request an informative title and description

2020-12-14 10:09 UTC, jhollway requested changes
Great, thanks @henriquesposito this is a big change set, but an important one. We need to make sure all front-facing documentation is nice and clean, correct, and comprehensible

2020-12-14 10:09 UTC, jhollway commented on R/standardise_dates.R
> +  if (stringr::str_detect(dates, "^[:digit:]{2}-[:digit:]{2}-[:digit:]{4}$")) { # Correct order and dates format if need
"^[:digit:]{1,2}-[:digit:]{1,2}-[:digit:]{4}$" might be more efficient?

2020-12-14 10:09 UTC, jhollway commented on R/standardise_dates.R
> +        paste(y,m,d,sep = "-")
Quite a bit going on here. Might be easier to debug in the future if we create internal helper functions for some of this work, but this can be raised as an issue for the future.

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +qData has package related functions that help developers contribute to the ecosystem of packages by helping with the set-up of packages
Please use `{qData}` for references to the package

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +qData::import_data("COW", 'states')
Why is one of these strings in double quotation marks and the other in single quotation marks? Could users think this is meaningful?

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +It requires that the package name starts with a the letter q as well as that
Quote "q" for clarity

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +These include, for example, the `transmutate ()` function which is between between dplyr's transmute and mutate but that returns
Parentheses need to be adjacent to function name

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +These include, for example, the `entitle()` function that capitalises all words in a string to enable comparison.
This is now `standardise_title()`

2020-12-14 10:09 UTC, jhollway commented on vignettes/developer.Rmd
> +transmutate(End = lubridate::dmy(edate))
Need to use `standardise_title()` and `standardise_dates()` here

2020-12-14 10:09 UTC, jhollway commented on vignettes/user.Rmd
> +author: "James Hollway"
Please check through and see whether this works for you also, whether there is anything you would wish clarified, and whether it works for you if you run `pkgdown::build_site()` locally.

2020-12-14 14:13 UTC, henriquesposito commented on README.md
> +# qData <img src="inst/qData_hexlogo.png" align="right" width="200"/>
I have updated the size of the white space around and width within the README document. Let me know what you think now or I can change once again.

2020-12-14 15:05 UTC, henriquesposito commented on vignettes/user.Rmd
> +author: "James Hollway"
It does not knit or build locally for me. I get an issue on lines 148-153 related to the dplyr::filter() not finding the ID variable... I cannot find out why.

2020-12-14 16:23 UTC, henriquesposito commented on R/standardise_dates.R
> +  if (stringr::str_detect(dates, "^[:digit:]{2}-[:digit:]{2}-[:digit:]{4}$")) { # Correct order and dates format if need
Yes, it is. However, if date is "^[:digit:]{1}-[:digit:]{2}-[:digit:]{4}$" it is more likely in mdy format. Though I do not think this is a very common format, but I still kept separate simply because of this. Should I still change to the more efficient form and oversee these unlike formats?

2020-12-14 16:31 UTC, jhollway commented on R/standardise_dates.R
> +  if (stringr::str_detect(dates, "^[:digit:]{2}-[:digit:]{2}-[:digit:]{4}$")) { # Correct order and dates format if need
We can also just inform users in the documentation that we only allow dmy and ymd at present (i.e. that mdy may introduce errors)

2020-12-14 17:52 UTC, henriquesposito commented on DESCRIPTION
>  Title: Quantum Data for the 21st Century
I do agree, but I do not know how to address this. If you want to change quantum for something else we can perhaps say something like "A package to deal with quantitative and qualitative data made for the 21st century". I am going to have a think about this...

2020-12-15 10:38 UTC, henriquesposito commented on vignettes/user.Rmd
> +author: "James Hollway"
It builds locally now. I like this vignette a lot, it is really informative and helpful!

2020-12-15 12:19 UTC, henriquesposito commented on vignettes/user.Rmd
> +author: "James Hollway"
Actually I am getting a new issue when trying to build locally now with lines 31-33 , the error appears to be with `get_packages()`... I will try and look in to it.

2021-01-06 17:08 UTC, jhollway approved these changes

2021-01-06 17:12 UTC, merged