Updated the vignette to account for changes in qData functions
globalgov/qData pull request #82
Opened 2021-01-08 09:38 UTC by EstherPeev

# Description

* Corrected the typing error found in the vignette "develop"
* Updated the description of the `export_data()` function to its new version including database name as a string
* Changed the description of the _Connecting data_ section to include `export_data()` specificities

Closes #81

# Checklist:

- [ ] I have corrected the typing error (two times the word "between") in the _Correcting data_ section
- [ ] I have updated the `export_data()` function description to include "states" as the second input
- [ ] I have updated the _Connecting data_ section to include `export_data()` function as the main function to connect the corrected datasets and form a three dimensional database

2021-01-08 09:50 UTC, jhollway requested changes

2021-01-08 09:50 UTC, jhollway commented on vignettes/developer.Rmd
>  used in the mutations. {qData} also includes functions that help correct and standardise dates.
{qData} and other package names should also be in code fences: `{qData}`

2021-01-08 09:50 UTC, jhollway commented on vignettes/developer.Rmd
> -This can be done with the help of several functions in {qData}.
There are also some outstanding style issues: in the review I can see them below. You can also access them [here](https://www.codefactor.io/repository/github/globalgov/qdata/issues). Can you please treat as many of them as you can @EstherPeev ?

2021-01-08 13:47 UTC, jhollway requested changes

2021-01-08 13:47 UTC, jhollway commented on .github/CONTRIBUTING.md
> +This outlines how to propose a change to a package from the Global Governance Observatory's ecosystem. Please note that the `qData` project is released with a [Contributor Code of Conduct](CODE_OF_CO
Put "By contributing..." onto a new line

2021-01-08 13:47 UTC, jhollway commented on .github/CONTRIBUTING.md
>  If you develop new code in `C++`, please follow the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html).
Not applicable here, could delete

2021-01-08 13:47 UTC, jhollway commented on .github/CONTRIBUTING.md
>     checks = all_checks()[-c(8)])
Maybe outline that these checks are incorporated into the checks made when a pull request is created/updated?

2021-01-08 13:47 UTC, jhollway commented on .github/CONTRIBUTING.md
> +The title of your PR should briefly describe the change. Please include a summary of the changes and which issues are fixed and the relevant motivation and context. List any dependencies that are req
You can make each of these sentences on a new line. Having sentences, or even clauses, on a new line can help with tracking line by line changes and avoiding the 80 character wrap limit. Perhaps emphasise this style guidance in CONTRIBUTING too?

2021-01-08 13:47 UTC, jhollway commented on .github/CONTRIBUTING.md
> +The title of your PR should briefly describe the change. Please include a summary of the changes and which issues are fixed and the relevant motivation and context. List any dependencies that are req
Perhaps add some guidance on how to write better, more structured commit messages too? https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

2021-01-08 13:47 UTC, jhollway commented on NEWS.md
> +* Changed the description of the Connecting data section to include export_data() specificities
Use code fences here too. Add a section header outlining that these changes are related to the package. See PR description...

2021-01-08 13:47 UTC, jhollway commented on vignettes/developer.Rmd
>  connected into a database. {qData} contains several functions geared towards data wrangling.
Can you put the package names in code fences too? Like this: `{package}`

2021-01-08 14:01 UTC, jhollway requested changes

2021-01-08 14:01 UTC, jhollway commented on .github/pull_request_template.md
>  Closes #(issue no.)
Show how this needs to be included in a bullet point and completed with an explanation

2021-01-08 14:01 UTC, jhollway commented on .github/pull_request_template.md
> +A pull request requires the different actions listed below to be completed. Please make sure you have been trough all of them by checking off the corresponding box once it has been done.
'trough' spelling. Please put individual sentences on new lines, also.

2021-01-08 16:06 UTC, jhollway commented
@EstherPeev don't forget to update the (original) checklist in the PR description and bump the DESCRIPTION file (I would call this a patch level update...)

2021-01-11 15:40 UTC, EstherPeev commented
@jhollway 
The checklist and DESCRIPTION file have been updated.

2021-01-12 10:45 UTC, jhollway requested changes

2021-01-12 10:45 UTC, jhollway commented on .github/CONTRIBUTING.md
> +It can help to use packages such as `lintr` and `goodpractice` to ensure these are followed. These packages are incorporated into the checks made when a pull request is made. The `styler` package fix
Separate into new lines.

2021-01-12 10:45 UTC, jhollway commented on .github/pull_request_template.md
>  Closes #(issue no.)
e.g. "Fixed #(issue no.) by rerouting A through B"

2021-01-12 10:45 UTC, jhollway commented on .github/pull_request_template.md
>  - [ ] I have commented my code in-line, particularly in hard-to-understand areas
Are these all clear to you? Should we rephrase/reorder them?

2021-01-12 10:45 UTC, jhollway commented on vignettes/developer.Rmd
> +two-dimensional datasets into three-dimensional databases that resembles a data cube (a list object where entries are dataframes).
Data frames, or rather tibbles?

2021-01-12 10:45 UTC, jhollway commented on vignettes/developer.Rmd
> +Corrected datasets can be connected to form a three dimensional database that resembles a data cube. The function creates a database in a data folder to store corrected datasets,while providing a cit
Separate into separate lines.

2021-01-12 10:45 UTC, jhollway commented on vignettes/developer.Rmd
> -This can be done with the help of several functions in {qData}.
Were you able to address most outstanding style issues?

2021-01-12 14:37 UTC, EstherPeev commented on .github/pull_request_template.md
>  - [ ] I have commented my code in-line, particularly in hard-to-understand areas
I think they are clear like this.

2021-01-12 14:40 UTC, EstherPeev commented
@jhollway 
I did the requested changes in the last commit. Should be all good hopefully.

2021-01-12 18:05 UTC, jhollway approved these changes

2021-01-12 18:06 UTC, jhollway commented
You can merge the pull request when you wish, @EstherPeev

2021-01-13 08:05 UTC, merged