Develop
globalgov/qData pull request #91
Opened 2021-01-25 09:38 UTC by EstherPeev

# Description

* Fixed #63 by setting up tests templates for the different types of database created. 
* Updated `setup_package()` function by removing license lines in the codes.
* Updated `standardize_dates()` function by making it works with `lubridate::as_date` and AD and negative historical dates
* Fixed #89 by adding templates appearing depending on the number of authors
* Setting up new function `report_data()` to make summarize of each database within a q package
* Added new type of contributor called *dtc* in the DESCRIPTION file

# Checklist:

- [X] I have commented my code in-line, particularly in hard-to-understand areas
- [X] My code follows the style guidelines of this project
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [X] The package builds on my OS without issues
- [X] My changes generate no new warnings
- [X] PR checks all pass for latest commit
- [X] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [X] I have updated NEWS.md with the same content as the description section of this pull request
- [X] I have given this pull request an informative title and description

2021-02-08 09:52 UTC, jhollway requested changes

2021-02-08 09:52 UTC, jhollway commented on DESCRIPTION
>               family = "Hollway",
Add Bernhard and Esther?

2021-02-08 09:52 UTC, jhollway commented on R/package_get.R
> +}
Add a new line after the final brace

2021-02-08 09:52 UTC, jhollway commented on R/package_setup.R
> +  family2 <- stringr::str_split(packageAuthor, "\\s|\\,")[[1]][4]
But how will this deal with individuals with three names? Do we infer only the last one is the surname? What if they are e.g. Spanish?

2021-02-08 09:52 UTC, jhollway commented on R/package_setup.R
> +}
Add new empty line at end

2021-02-08 09:52 UTC, jhollway commented on R/package_setup.R
>    usethis::ui_done("Added CCBY license. Modify if necessary.")
If no longer creating license automatically, then don't report it as done

2021-02-08 09:52 UTC, jhollway commented on R/plot_releases.R
> +#' @source https://benalexkeen.com/creating-a-timeline-graphic-using-r-and-ggplot2/
Add @examples for qData?

2021-02-08 09:52 UTC, jhollway commented on R/plot_releases.R
> +}
Add new empty line at the end

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +#' }
Remove \dontrun so that we can see what it does on the website...

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +    else{
Best practice to put else on same line as close brace from previous condition, e.g. `} else {`

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +  else{
Best practice to put else on same line as close brace from previous condition, e.g. } else {

2021-02-08 09:52 UTC, jhollway commented on R/standardise_titles.R
> +}
Best practice to leave an empty line at the end of scripts

2021-02-08 09:52 UTC, jhollway commented on R/utility.R
> +
If we add this in this version, maybe document it a little better.

Add an issue for a future version that has a GitHub lookup if it can't find the package on CRAN?

2021-02-08 09:52 UTC, jhollway commented on R/utility.R
> +#' Helper function for removing all other
Incomplete title?

2021-02-08 09:52 UTC, jhollway commented on R/utility.R
> +#' @param keep A vector containing the name of variables which you wish to keep
Explain in `@details` a bit more?

2021-02-08 09:52 UTC, jhollway commented on R/utility.R
> +}
Add new line at end

2021-02-08 09:52 UTC, jhollway commented on R/wrangling.R
> +}
Add new line at end?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/qPackage-DESC.dcf
> +RoxygenNote: 7.1.1
Does it need a new line at the end?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/qPackage-DESC.dcf
> +             role = c("cre", "aut", "ctb", "dtc")))
But actually, aren't these often separate roles?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/qPackage-DESC2.dcf
> +Title: Quantum Data for the 21st Century
Replace this with a more typical placeholder title?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/qPackage-DESC2.dcf
> +RoxygenNote: 7.1.1
New line?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/test_agreements.R
> +library(pointblank)
Maybe we can remove this if pointblank is a dependency for qData anyway?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/test_agreements.R
> +#   expect_message(tibble::is_tibble("{{{dat}}}"), "TRUE")
What are these lines here for? Remove?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/test_agreements.R
> +})
New line?

2021-02-08 09:52 UTC, jhollway commented on inst/templates/test_general.R
> +})
New line?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_export_data.R
> +# # create_local_package() function is not currently working.
Open as new issue?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_export_data.R
> +# # }
New line?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_plot_releases.R
> +# })
Is the plan still to test this function? I would suggest renaming the object away from a name that we are using for a package in this ecosystem.

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_report_data.R
> +})
Could these tests be overly sensitive to (potentially independent) development in the qStates package?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_reunite.R
> +})
New line?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_standardise_dates.R
> +})
New line?

2021-02-08 09:52 UTC, jhollway commented on tests/testthat/test_standardise_dates.R
> +})
Maybe add an issue to simplify some of these tests by making them a vector rather than e.g. here three separate lines/tests.

2021-02-08 09:52 UTC, jhollway commented on vignettes/user.Rmd
> -purrr::map(states, md.pattern, rotate.names = T)
I still like the idea of demonstrating what we can do if we have lists of data though. Perhaps we can add an issue to build back out this vignette with more demonstrative examples.

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +report_data <- function(pkg, dbase=NULL, dset=NULL){
We should think about making sure we have consistent argument names/terminology across the package. I.e. is it `database` (`export_data()`) or `dbase` (here)?

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +      tabl <- data.frame(UniqueID = length(unique(ds$ID)),
I can see why you are using a data frame @BBieri , but the danger is that we get many lines...

2021-02-08 09:52 UTC, jhollway commented on R/report_data.R
> +    colnames(tabl3) <- c("Unique ID", "Missing data", "Rows", "Columns", "Beg", "End", "Link", "Bibliography")
- "Missing data" can be dealt with in a new `compare_data()` function
- "Unique ID", "Rows", and "Columns" should be numeric not character/string
- leave the link for somewhere else in the documentation; we are trying to make it easier for researchers to use this data and not need to run around the web
- call it "Citation" or "Reference", not "Bibliography"

2021-02-08 09:52 UTC, jhollway commented on R/data_import.R
> +      import_type <- "load"
Need to document in NEWS that RData is now also accepted as an import file type

2021-02-08 09:52 UTC, jhollway commented on NEWS.md
> +* Closes #94 by adding a bibliographic attribute to each dataset with `export_data()`
Keep consistent use of past tense, i.e. Closed not Closes

2021-02-08 09:52 UTC, jhollway commented on NEWS.md
> +* Closes #93 by setting up internal helper functions for `standardise_dates()`
Cluster issues/news items together by common related function. E.g. all these issues relate to `standardise_dates()`, and the following all relate to `export_data()`

2021-02-08 09:52 UTC, jhollway commented on R/data_export.R
> +#' a documentation script to help documenting data sources and describing variables.
Line more than 80 characters?

2021-02-08 09:52 UTC, jhollway commented on R/data_export.R
> +export_data <- function(..., database, link) {
Is `link` argument clear enough? Maybe `url`? Should this be to source (i.e. a download link) or to documentation or project website?

2021-02-08 09:52 UTC, jhollway commented on R/data_export.R
> +              path = getwd())
Great! Will we add one for memberships too?

2021-02-08 09:52 UTC, jhollway commented on R/standardise_dates.R
> +#' into a range of dates
Need to elaborate the description of this function a bit if this is a centrepiece of the package

2021-02-08 09:52 UTC, jhollway commented on R/standardise_dates.R
>  #' Create nested vectors of dates from vague date inputs
Revisit function documentation title, if it is about standardising all dates rather than just treating vague date inputs

2021-02-08 09:52 UTC, jhollway commented on R/standardise_dates.R
> +  # dates <- ifelse(stringr::str_detect(dates, "^[:digit:]{4}$"), NA, dates) # for now, the function will treat date range as NA
Might want to add an issue to refactor all this in the future, @henriquesposito

2021-02-08 09:52 UTC, jhollway commented on R/standardise_dates.R
> +}
New line?

2021-02-08 10:35 UTC, BBieri commented on R/report_data.R
> +      tabl <- data.frame(UniqueID = length(unique(ds$ID)),
In this case, we will get maximum one line actually since the user specified a specific (and unique) dataframe's metadata to be displayed. I will open an issue for a future release to allow users to specify a subset of datasets of a given database (with a vector as input) and will then implement a similar structure than in the case of database and package metadata display. Does this sound good @jhollway ?

2021-02-08 12:49 UTC, henriquesposito commented on R/package_setup.R
> +  family2 <- stringr::str_split(packageAuthor, "\\s|\\,")[[1]][4]
I updated the packageAuthor parameter documentation to inform users, for now, that only 2 names are taken. I also created an issue to improve this feature by accepting more names and more author for the next PR.

2021-02-08 15:51 UTC, henriquesposito commented on R/data_export.R
> +              path = getwd())
Yes, that is the thinking as we decide on what kinds of objects can be contained in qData packages (actors, agreements, relations, etc). This means we can create specific test for these databases as they are added.

2021-02-08 17:11 UTC, henriquesposito commented on inst/templates/qPackage-DESC2.dcf
> +Title: Quantum Data for the 21st Century
Yes, they can be separate roles. I will make sure to add this aspect on the issue created for author names to make sure role is also better distinguished by the `setup_package()` function.

2021-02-08 17:15 UTC, henriquesposito commented on inst/templates/qPackage-DESC.dcf
> +             role = c("cre", "aut", "ctb", "dtc")))
Yes, they can be separate roles. I will make sure to add this aspect on the issue created for author names to make sure role is also better distinguished by the `setup_package()` function.

2021-02-08 18:33 UTC, henriquesposito commented on tests/testthat/test_report_data.R
> +})
Yes, you are right. I opened a new issue to deal with testing the function in different ways so that this does not become an issue in the future.

2021-02-08 19:38 UTC, jhollway reviewed
Nearly there, just a few suggestions to tidy up a couple of things.

2021-02-08 19:38 UTC, jhollway commented on DESCRIPTION
> +             comment = "IHEID"),
Do you want to add your ORCID @henriquesposito ?

2021-02-08 19:38 UTC, jhollway commented on NEWS.md
> +* Replaced the old logo with a new one.
A suggestion for ordering this section (and the PR description):

* Replaced the old logo with a new one.
* Closed #83 by improving CII best practices score
 * Added `depends()` helper function for loading and, if necessary, installing CRAN packages
 * Added `plot_releases()` function that visualises historical milestones/releases for GitHub repositories
* Updated `setup_package()` function by removing license lines in the codes.
  * Fixed #89 by adding different description templates depending on the number of authors declared in `setup_package()`
  * Added new type of contributor called *dtc* in the DESCRIPTION file

And then actually `report_data()` is more of a **Connection**-related function, or?

* Closed #78 by creating `report_data()` function that displays information on the data within a qPackage

2021-02-08 19:38 UTC, jhollway commented on R/package_setup.R
> +     qtemplate("qPackage-DESC2.dcf",
So what happens with the original DESC now?

2021-02-08 19:38 UTC, jhollway commented on R/package_setup.R
> -  usethis::ui_done("Added CCBY license. Modify if necessary.")
Is any License added now, or are we expecting contributors to do this themselves?

2021-02-08 19:38 UTC, jhollway commented on R/plot_releases.R
> +#' or more usefully, a Github repository listing.
What does it @return?

2021-02-08 19:38 UTC, jhollway commented on R/utility.R
> +#' regular expression or both.
Isn't this function more about which objects from the global environment you want to keep?

2021-02-08 19:38 UTC, jhollway commented on inst/templates/qPackage-DESC.dcf
> +Title: A Package for the qData Ecosystem
Excellent!

2021-02-08 19:38 UTC, jhollway commented on inst/templates/test_general.R
> +  expect_false(any(grepl("^N/A$", {{{dab}}}[["{{{dat}}}"]])))
What does the first one check for? Are there other common NA codes we want to check for?

2021-02-09 08:00 UTC, henriquesposito commented on R/package_setup.R
> -  usethis::ui_done("Added CCBY license. Modify if necessary.")
A standard CCBY 4.0 license is added in the description template.

2021-02-09 08:05 UTC, henriquesposito commented on R/package_setup.R
> +     qtemplate("qPackage-DESC2.dcf",
There are two DESC files now, one is called if one author is declared and the other if two authors are declared; other than that they are equivalent. This should be modified once we find better ways to accept multiple authors and multiple names in `setup_package()`. Issues for these have already been open.

2021-02-09 09:02 UTC, jhollway requested changes

2021-02-09 10:51 UTC, jhollway approved these changes

2021-02-09 11:43 UTC, merged